### ISSUE TITLE
 Column not found Exception when preview a membership

### ISSUE THREAD

**Issue by chrisvidal** [responsiv/subscribe-plugin#6]
From backend, `/backend/responsiv/subscribe/memberships/preview/1`

```php
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'membership_id' in 'where clause' (SQL: select * from `responsiv_subscribe_schedules` where `membership_id` = 9 and `billing_period` >= 1)
```

**Comment by daftspunk** [comment]
Hey Chris. I never finished this plugin, sorry. It became too complicated. Was hoping someone could learn from it

**Comment by chrisvidal** [comment]
I would love to finish it, I can see lots of potential with it

**Comment by chrisvidal** [comment]
Do you know what is left in the todo list?

**Comment by chrisvidal** [comment]
I am actually planning to use it for a project, maybe it is not a good idea :)

**Comment by daftspunk** [comment]
Well, its mostly all there. I recall that there were too many possible combinations with subscriptions and the design became complicated. If you have a simple use case, this could be a valuable resource for designing an implementation

However you're right, using this plugin in its current form would not be a good idea since it is unfinished
